import "~/styles/globals.css";
import { Analytics } from "@vercel/analytics/react"
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {Suspense} from "react";
import TopNav from "~/app/_components/TopNav";

export const metadata: Metadata = {
  title: "DebateFlow",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/flowlogo.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
      <TopNav />
      <Suspense>
      {children}
      </Suspense>
      <Analytics/>
      </body>
    </html>
  );
}
